### ISSUE TITLE
Problem on 1.9

### ISSUE THREAD

**Issue by fmohican** [Alex-The-Coder/BetterEnchants#2]
If you can fix.... Thanks you!

============CONSOLE ERROR==================
[10:09:45 ERROR]: Could not pass event InventoryClickEvent to BetterEnchants v3.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-6f291ea-55a8535]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-6f291ea-55a8535]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-6f291ea-55a8535]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1844) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-6f291ea-55a8535]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [server.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [server.jar:git-Spigot-6f291ea-55a8535]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoSuchFieldError: ANVIL_USE
        at me.AlexTheCoder.BetterEnchants.crystal.CrystalEnchantMenu.applyEnchants(CrystalEnchantMenu.java:55) ~[?:?]
        at me.AlexTheCoder.BetterEnchants.crystal.CrystalEnchantListener.onPickItem(CrystalEnchantListener.java:92) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-6f291ea-55a8535]
        ... 15 more

**Comment by alexjmeech** [comment]
Will be fixed in next release

**Comment by fmohican** [comment]
Thanks you!
